apiVersion: v1
kind: Service
metadata:
  name: auth-node-app
  namespace: argo-node-app
spec:
  type: NodePort
  selector:
    app: auth-node-app
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      nodePort: 30690
